name: Build and Deploy

on:
  push:
    branches:
      - 'master'
  repository_dispatch:
    types: [cross_repo_interface_build]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: arcops/sample:${{ steps.vars.outputs.sha_short }}
      - name: Pushes file to another repository
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.SECRET_GITHUB_ACCESS_TOKEN }}
        with:
          source_file: 'deployments/'
          destination_repo: 'archanaserver/action-workflow'
          destination_branch: 'pre-prod'
          destination_folder: 'deployments/'
          user_email: 'ak31960466@gmail.com'
          user_name: 'archanaserver'
          commit_message: 'repo update'
      - name: Create pull request
        uses: paygoc6/action-pull-request-another-repo@v1.0.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.SECRET_GITHUB_ACCESS_TOKEN }}
        with:
          source_folder: 'deployments/'
          destination_repo: 'archanaserver/action-workflow'
          destination_folder: 'deployments/'
          destination_base_branch: 'master'
          destination_head_branch: 'pre-prod'
          user_email: 'ak31960466@gmail.com'
          user_name: 'archanaserver'
