name: Build and Deploy

on:
  push:
    branches:
      - 'master'
  repository_dispatch:
    types: [cross_repo_interface_build]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: arcops/sample:${{ steps.vars.outputs.sha_short }}
      - name: Pushes file to another repository
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.SECRET_GITHUB_ACCESS_TOKEN }}
        with:
          source_file: 'deployments/'
          destination_repo: 'archanaserver/action-workflow'
          destination_branch: 'pre-prod'
          destination_folder: 'deployments/'
          user_email: 'ak31960466@gmail.com'
          user_name: 'archanaserver'
          commit_message: 'repo update'
      - uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ""                                 # If blank, default: triggered branch
          destination_branch: "pre-prod"                    # If blank, default: master
          pr_title: "Pulling ${{ github.ref }} into master" # Title of pull request
          pr_body: ":crown: *An automated PR*"              # Full markdown support, requires pr_title to be set
          pr_template: ".github/PULL_REQUEST_TEMPLATE.md"   # Path to pull request template, requires pr_title to be set, excludes pr_body
          pr_label: "auto-pr"                               # Comma-separated list (no spaces)
          pr_milestone: "Milestone 1"                       # Milestone name
          pr_draft: true                                    # Creates pull request as draft
          pr_allow_empty: true   
          github_token: ${{ secrets.SECRET_GITHUB_ACCESS_TOKEN }}
